export const TEMPLATE_BY_ID: TemplateById = {
  0: { name: "Test Landing Page", niche: "landing-page", categ: 1, price: 80 },
  1: {
    name: "Modern Landing Page",
    niche: "landing-page",
    categ: 2,
    price: 49,
  },
  2: { name: "Fantasy Sports Hub", niche: "landing-page", categ: 2, price: 79 },
  3: { name: "Casino Social Site", niche: "landing-page", categ: 3, price: 89 },
  4: { name: "E-commerce Express", niche: "landing-page", categ: 4, price: 59 },
  5: {
    name: "Sports Betting Platform",
    niche: "landing-page",
    categ: 2,
    price: 99,
  },
  6: { name: "Social Casino Hub", niche: "landing-page", categ: 3, price: 75 },
  7: {
    name: "Shop Smart E-commerce",
    niche: "landing-page",
    categ: 4,
    price: 55,
  },
  8: {
    name: "Luxury Landing Page",
    niche: "landing-page",
    categ: 3,
    price: 69,
  },
  9: { name: "Online Poker Arena", niche: "landing-page", categ: 3, price: 95 },
  10: {
    name: "Minimalist E-commerce",
    niche: "landing-page",
    categ: 4,
    price: 45,
  },
  11: {
    name: "Gaming Fantasy League",
    niche: "landing-page",
    categ: 2,
    price: 85,
  },
  12: {
    name: "E-commerce Marketplace",
    niche: "landing-page",
    categ: 4,
    price: 65,
  },
  13: {
    name: "Creative Landing Page",
    niche: "landing-page",
    categ: 2,
    price: 50,
  },
  14: { name: "Casino VIP Club", niche: "landing-page", categ: 3, price: 99 },
  15: {
    name: "E-commerce Fashion Hub",
    niche: "landing-page",
    categ: 4,
    price: 60,
  },
  16: {
    name: "Fantasy Sports Hub 2.0",
    niche: "landing-page",
    categ: 2,
    price: 89,
  },
  17: {
    name: "Interactive Casino Site",
    niche: "landing-page",
    categ: 3,
    price: 95,
  },
  18: {
    name: "Landing Page Showcase",
    niche: "landing-page",
    categ: 4,
    price: 52,
  },
  19: {
    name: "E-commerce for Creators",
    niche: "landing-page",
    categ: 4,
    price: 58,
  },
  20: {
    name: "Virtual Casino Games",
    niche: "landing-page",
    categ: 3,
    price: 90,
  },
  21: {
    name: "Fantasy Sports Dashboard",
    niche: "landing-page",
    categ: 2,
    price: 99,
  },
  22: {
    name: "E-commerce Digital Store",
    niche: "landing-page",
    categ: 4,
    price: 60,
  },
  23: {
    name: "Modern Casino Experience",
    niche: "landing-page",
    categ: 3,
    price: 95,
  },
  24: {
    name: "Premium Landing Page",
    niche: "landing-page",
    categ: 3,
    price: 70,
  },
  25: {
    name: "E-commerce Grocery Store",
    niche: "landing-page",
    categ: 4,
    price: 55,
  },
  26: {
    name: "Fantasy Sports Betting",
    niche: "landing-page",
    categ: 2,
    price: 92,
  },
  27: { name: "Casino Games Hub", niche: "landing-page", categ: 3, price: 88 },
  28: {
    name: "Simple E-commerce Site",
    niche: "landing-page",
    categ: 4,
    price: 48,
  },
  29: {
    name: "Sport Fantasy League 2025",
    niche: "landing-page",
    categ: 2,
    price: 99,
  },
  30: {
    name: "Casino Tournament Platform",
    niche: "landing-page",
    categ: 3,
    price: 98,
  },
  31: {
    name: "Creative E-commerce Shop",
    niche: "landing-page",
    categ: 4,
    price: 62,
  },
  32: {
    name: "Landing Page Professional",
    niche: "landing-page",
    categ: 3,
    price: 55,
  },
  33: {
    name: "Exclusive Fantasy Sports",
    niche: "landing-page",
    categ: 2,
    price: 97,
  },
  34: { name: "Casino Club Hub", niche: "landing-page", categ: 3, price: 90 },
  35: {
    name: "E-commerce Marketplace 2.0",
    niche: "landing-page",
    categ: 4,
    price: 66,
  },
  36: {
    name: "Gaming Fantasy League Pro",
    niche: "landing-page",
    categ: 2,
    price: 94,
  },
  37: {
    name: "Luxury Casino Site",
    niche: "landing-page",
    categ: 3,
    price: 99,
  },
  38: { name: "Tech Landing Page", niche: "landing-page", categ: 4, price: 58 },
  39: {
    name: "E-commerce Tech Shop",
    niche: "landing-page",
    categ: 4,
    price: 65,
  },
  40: {
    name: "Fantasy Sports 2025",
    niche: "landing-page",
    categ: 2,
    price: 93,
  },
  41: {
    name: "Casino Games Arena",
    niche: "landing-page",
    categ: 3,
    price: 89,
  },
  42: {
    name: "Premium E-commerce Store",
    niche: "landing-page",
    categ: 4,
    price: 67,
  },
  43: {
    name: "Modern Fantasy Sports",
    niche: "landing-page",
    categ: 2,
    price: 91,
  },
  44: {
    name: "Casino Night Online",
    niche: "landing-page",
    categ: 3,
    price: 96,
  },
  45: {
    name: "Landing Page Boost",
    niche: "landing-page",
    categ: 2,
    price: 56,
  },
  46: {
    name: "Smart E-commerce Store",
    niche: "landing-page",
    categ: 4,
    price: 59,
  },
  47: {
    name: "Global Fantasy League",
    niche: "landing-page",
    categ: 2,
    price: 88,
  },
  48: {
    name: "Casino Roulette Site",
    niche: "landing-page",
    categ: 3,
    price: 97,
  },
  49: {
    name: "Elegant Landing Page",
    niche: "landing-page",
    categ: 5,
    price: 61,
  },
  50: {
    name: "Digital Goods E-commerce",
    niche: "landing-page",
    categ: 4,
    price: 63,
  },
  51: {
    name: "Fantasy Sports PRO",
    niche: "landing-page",
    categ: 2,
    price: 98,
  },
  52: {
    name: "Slots Casino Online",
    niche: "landing-page",
    categ: 3,
    price: 95,
  },
  53: {
    name: "Landing Page Creator",
    niche: "landing-page",
    categ: 1,
    price: 54,
  },
  54: {
    name: "Artisan E-commerce",
    niche: "landing-page",
    categ: 4,
    price: 60,
  },
  55: {
    name: "Pro Fantasy Sports",
    niche: "landing-page",
    categ: 2,
    price: 96,
  },
  56: {
    name: "Online Blackjack Hub",
    niche: "landing-page",
    categ: 3,
    price: 94,
  },
  57: {
    name: "Landing Page Focus",
    niche: "landing-page",
    categ: 1,
    price: 52,
  },
  58: {
    name: "Modern Shop E-commerce",
    niche: "landing-page",
    categ: 4,
    price: 62,
  },
  59: {
    name: "Ultimate Fantasy League",
    niche: "landing-page",
    categ: 2,
    price: 99,
  },
  60: {
    name: "Vegas Online Casino",
    niche: "landing-page",
    categ: 3,
    price: 99,
  },

  61: {
    name: "Sport Fantasy Template 1",
    niche: "sport-fantasy",
    categ: 5,
    price: 84,
  },
  62: {
    name: "Sport Fantasy Template 2",
    niche: "sport-fantasy",
    categ: 6,
    price: 56,
  },
  63: {
    name: "Sport Fantasy Template 3",
    niche: "sport-fantasy",
    categ: 7,
    price: 61,
  },
  64: {
    name: "Sport Fantasy Template 4",
    niche: "sport-fantasy",
    categ: 6,
    price: 72,
  },
  65: {
    name: "Sport Fantasy Template 5",
    niche: "sport-fantasy",
    categ: 7,
    price: 96,
  },
  66: {
    name: "Sport Fantasy Template 6",
    niche: "sport-fantasy",
    categ: 5,
    price: 43,
  },
  67: {
    name: "Sport Fantasy Template 7",
    niche: "sport-fantasy",
    categ: 6,
    price: 62,
  },
  68: {
    name: "Sport Fantasy Template 8",
    niche: "sport-fantasy",
    categ: 5,
    price: 90,
  },
  69: {
    name: "Sport Fantasy Template 9",
    niche: "sport-fantasy",
    categ: 6,
    price: 79,
  },
  70: {
    name: "Sport Fantasy Template 10",
    niche: "sport-fantasy",
    categ: 7,
    price: 55,
  },
  71: {
    name: "Sport Fantasy Template 11",
    niche: "sport-fantasy",
    categ: 7,
    price: 48,
  },
  72: {
    name: "Sport Fantasy Template 12",
    niche: "sport-fantasy",
    categ: 5,
    price: 83,
  },
  73: {
    name: "Sport Fantasy Template 13",
    niche: "sport-fantasy",
    categ: 6,
    price: 73,
  },
  74: {
    name: "Sport Fantasy Template 14",
    niche: "sport-fantasy",
    categ: 6,
    price: 61,
  },
  75: {
    name: "Sport Fantasy Template 15",
    niche: "sport-fantasy",
    categ: 5,
    price: 67,
  },
  76: {
    name: "Sport Fantasy Template 16",
    niche: "sport-fantasy",
    categ: 7,
    price: 87,
  },
  77: {
    name: "Sport Fantasy Template 17",
    niche: "sport-fantasy",
    categ: 7,
    price: 60,
  },
  78: {
    name: "Sport Fantasy Template 18",
    niche: "sport-fantasy",
    categ: 5,
    price: 89,
  },
  79: {
    name: "Sport Fantasy Template 19",
    niche: "sport-fantasy",
    categ: 6,
    price: 64,
  },
  80: {
    name: "Sport Fantasy Template 20",
    niche: "sport-fantasy",
    categ: 6,
    price: 71,
  },
  81: {
    name: "Sport Fantasy Template 21",
    niche: "sport-fantasy",
    categ: 7,
    price: 95,
  },
  82: {
    name: "Sport Fantasy Template 22",
    niche: "sport-fantasy",
    categ: 6,
    price: 88,
  },
  83: {
    name: "Sport Fantasy Template 23",
    niche: "sport-fantasy",
    categ: 5,
    price: 59,
  },
  84: {
    name: "Sport Fantasy Template 24",
    niche: "sport-fantasy",
    categ: 5,
    price: 90,
  },
  85: {
    name: "Sport Fantasy Template 25",
    niche: "sport-fantasy",
    categ: 7,
    price: 92,
  },
  86: {
    name: "Sport Fantasy Template 26",
    niche: "sport-fantasy",
    categ: 7,
    price: 78,
  },
  87: {
    name: "Sport Fantasy Template 27",
    niche: "sport-fantasy",
    categ: 6,
    price: 55,
  },
  88: {
    name: "Sport Fantasy Template 28",
    niche: "sport-fantasy",
    categ: 5,
    price: 66,
  },
  89: {
    name: "Sport Fantasy Template 29",
    niche: "sport-fantasy",
    categ: 7,
    price: 93,
  },
  90: {
    name: "Sport Fantasy Template 30",
    niche: "sport-fantasy",
    categ: 6,
    price: 53,
  },
  91: {
    name: "Sport Fantasy Template 31",
    niche: "sport-fantasy",
    categ: 5,
    price: 87,
  },
  92: {
    name: "Sport Fantasy Template 32",
    niche: "sport-fantasy",
    categ: 7,
    price: 68,
  },
  93: {
    name: "Sport Fantasy Template 33",
    niche: "sport-fantasy",
    categ: 6,
    price: 76,
  },
  94: {
    name: "Sport Fantasy Template 34",
    niche: "sport-fantasy",
    categ: 5,
    price: 85,
  },
  95: {
    name: "Sport Fantasy Template 35",
    niche: "sport-fantasy",
    categ: 7,
    price: 52,
  },
  96: {
    name: "Sport Fantasy Template 36",
    niche: "sport-fantasy",
    categ: 6,
    price: 79,
  },
  97: {
    name: "Sport Fantasy Template 37",
    niche: "sport-fantasy",
    categ: 6,
    price: 88,
  },
  98: {
    name: "Sport Fantasy Template 38",
    niche: "sport-fantasy",
    categ: 7,
    price: 61,
  },
  99: {
    name: "Sport Fantasy Template 39",
    niche: "sport-fantasy",
    categ: 5,
    price: 82,
  },
  100: {
    name: "Sport Fantasy Template 40",
    niche: "sport-fantasy",
    categ: 6,
    price: 95,
  },
  101: {
    name: "Sport Fantasy Template 41",
    niche: "sport-fantasy",
    categ: 7,
    price: 55,
  },
  102: {
    name: "Sport Fantasy Template 42",
    niche: "sport-fantasy",
    categ: 5,
    price: 80,
  },
  103: {
    name: "Sport Fantasy Template 43",
    niche: "sport-fantasy",
    categ: 6,
    price: 74,
  },
  104: {
    name: "Sport Fantasy Template 44",
    niche: "sport-fantasy",
    categ: 5,
    price: 66,
  },
  105: {
    name: "Sport Fantasy Template 45",
    niche: "sport-fantasy",
    categ: 6,
    price: 84,
  },
  106: {
    name: "Sport Fantasy Template 46",
    niche: "sport-fantasy",
    categ: 7,
    price: 72,
  },
  107: {
    name: "Sport Fantasy Template 47",
    niche: "sport-fantasy",
    categ: 6,
    price: 49,
  },
  108: {
    name: "Sport Fantasy Template 48",
    niche: "sport-fantasy",
    categ: 5,
    price: 91,
  },
  109: {
    name: "Sport Fantasy Template 49",
    niche: "sport-fantasy",
    categ: 7,
    price: 63,
  },
  110: {
    name: "Sport Fantasy Template 50",
    niche: "sport-fantasy",
    categ: 6,
    price: 81,
  },
  111: {
    name: "Sport Fantasy Template 51",
    niche: "sport-fantasy",
    categ: 5,
    price: 60,
  },
  112: {
    name: "Sport Fantasy Template 52",
    niche: "sport-fantasy",
    categ: 7,
    price: 59,
  },
  113: {
    name: "Sport Fantasy Template 53",
    niche: "sport-fantasy",
    categ: 6,
    price: 93,
  },
  114: {
    name: "Sport Fantasy Template 54",
    niche: "sport-fantasy",
    categ: 7,
    price: 70,
  },
  115: {
    name: "Sport Fantasy Template 55",
    niche: "sport-fantasy",
    categ: 5,
    price: 65,
  },
  116: {
    name: "Sport Fantasy Template 56",
    niche: "sport-fantasy",
    categ: 5,
    price: 58,
  },
  117: {
    name: "Sport Fantasy Template 57",
    niche: "sport-fantasy",
    categ: 7,
    price: 69,
  },
  118: {
    name: "Sport Fantasy Template 58",
    niche: "sport-fantasy",
    categ: 6,
    price: 75,
  },
  119: {
    name: "Sport Fantasy Template 59",
    niche: "sport-fantasy",
    categ: 7,
    price: 86,
  },

  120: {
    name: "Lucky Spins",
    niche: "social-casino",
    categ: 10,
    price: 49,
  },
  121: {
    name: "Casino Royale",
    niche: "social-casino",
    categ: 11,
    price: 65,
  },
  122: {
    name: "Jackpot Nights",
    niche: "social-casino",
    categ: 12,
    price: 79,
  },
  123: {
    name: "Vegas Fever",
    niche: "social-casino",
    categ: 9,
    price: 55,
  },
  124: {
    name: "Slot Mania",
    niche: "social-casino",
    categ: 8,
    price: 39,
  },
  125: {
    name: "High Roller Club",
    niche: "social-casino",
    categ: 10,
    price: 72,
  },
  126: {
    name: "Spin City",
    niche: "social-casino",
    categ: 12,
    price: 61,
  },
  127: {
    name: "Jackpot Jungle",
    niche: "social-casino",
    categ: 8,
    price: 43,
  },
  128: {
    name: "Roulette Rush",
    niche: "social-casino",
    categ: 9,
    price: 58,
  },
  129: {
    name: "Blackjack Nights",
    niche: "social-casino",
    categ: 11,
    price: 67,
  },
  130: {
    name: "Bingo Bling",
    niche: "social-casino",
    categ: 12,
    price: 54,
  },
  131: {
    name: "Casino Carnival",
    niche: "social-casino",
    categ: 9,
    price: 40,
  },
  132: {
    name: "Golden Reels",
    niche: "social-casino",
    categ: 10,
    price: 63,
  },
  133: {
    name: "VIP Slots",
    niche: "social-casino",
    categ: 8,
    price: 35,
  },
  134: {
    name: "Spin & Win",
    niche: "social-casino",
    categ: 11,
    price: 68,
  },
  135: {
    name: "Vegas Nights",
    niche: "social-casino",
    categ: 9,
    price: 59,
  },
  136: {
    name: "Big Win City",
    niche: "social-casino",
    categ: 12,
    price: 78,
  },
  137: {
    name: "Casino Galaxy",
    niche: "social-casino",
    categ: 8,
    price: 32,
  },
  138: {
    name: "Royal Flush Fun",
    niche: "social-casino",
    categ: 10,
    price: 70,
  },
  139: {
    name: "Mega Spins",
    niche: "social-casino",
    categ: 11,
    price: 64,
  },
  140: {
    name: "Spin Kingdom",
    niche: "social-casino",
    categ: 12,
    price: 81,
  },
  141: {
    name: "Reel Empire",
    niche: "social-casino",
    categ: 8,
    price: 37,
  },
  142: {
    name: "High Stakes Hub",
    niche: "social-casino",
    categ: 9,
    price: 56,
  },
  143: {
    name: "Vegas Vibes",
    niche: "social-casino",
    categ: 10,
    price: 62,
  },
  144: {
    name: "Slot Festival",
    niche: "social-casino",
    categ: 11,
    price: 73,
  },
  145: {
    name: "Roulette Royale",
    niche: "social-casino",
    categ: 12,
    price: 80,
  },
  146: {
    name: "Jackpot Island",
    niche: "social-casino",
    categ: 8,
    price: 41,
  },
  147: {
    name: "Casino Dreams",
    niche: "social-casino",
    categ: 9,
    price: 50,
  },
  148: {
    name: "Super Slots",
    niche: "social-casino",
    categ: 10,
    price: 60,
  },
  149: {
    name: "Blackjack Bash",
    niche: "social-casino",
    categ: 11,
    price: 69,
  },
  150: {
    name: "Slot Rush",
    niche: "social-casino",
    categ: 12,
    price: 75,
  },
  151: {
    name: "Spin Masters",
    niche: "social-casino",
    categ: 8,
    price: 44,
  },
  152: {
    name: "Reel Fortune",
    niche: "social-casino",
    categ: 9,
    price: 51,
  },
  153: {
    name: "Casino Clash",
    niche: "social-casino",
    categ: 10,
    price: 66,
  },
  154: {
    name: "Vegas Royale",
    niche: "social-casino",
    categ: 11,
    price: 71,
  },
  160: {
    name: "Mega Jackpot",
    niche: "ecommerce",
    categ: 13,
    price: 48,
  },
  161: {
    name: "Casino Clash Royale",
    niche: "ecommerce",
    categ: 14,
    price: 62,
  },
  162: {
    name: "Lucky Fortune",
    niche: "ecommerce",
    categ: 13,
    price: 54,
  },
  163: {
    name: "Roulette Star",
    niche: "ecommerce",
    categ: 14,
    price: 66,
  },
  164: {
    name: "Slot Magic",
    niche: "ecommerce",
    categ: 13,
    price: 73,
  },
  165: {
    name: "Vegas Power",
    niche: "ecommerce",
    categ: 14,
    price: 59,
  },
  166: {
    name: "Reel Kings",
    niche: "ecommerce",
    categ: 13,
    price: 77,
  },
  167: {
    name: "Lucky Spin Club",
    niche: "ecommerce",
    categ: 14,
    price: 45,
  },
  168: {
    name: "Casino Palms",
    niche: "ecommerce",
    categ: 13,
    price: 68,
  },
  169: {
    name: "Slot Odyssey",
    niche: "ecommerce",
    categ: 14,
    price: 54,
  },
  170: {
    name: "Bingo Jackpot",
    niche: "ecommerce",
    categ: 13,
    price: 60,
  },
  171: {
    name: "Spin Fest",
    niche: "ecommerce",
    categ: 14,
    price: 51,
  },
  172: {
    name: "Golden Vegas",
    niche: "ecommerce",
    categ: 13,
    price: 64,
  },
  173: {
    name: "Jackpot Royale",
    niche: "ecommerce",
    categ: 14,
    price: 79,
  },
  174: {
    name: "Spin Legends",
    niche: "ecommerce",
    categ: 13,
    price: 82,
  },
  175: {
    name: "High Stakes Jackpot",
    niche: "ecommerce",
    categ: 14,
    price: 56,
  },
  176: {
    name: "Slot Blitz",
    niche: "ecommerce",
    categ: 13,
    price: 63,
  },
  177: {
    name: "Vegas Nights Slot",
    niche: "ecommerce",
    categ: 14,
    price: 58,
  },
  178: {
    name: "Casino Galaxy Jackpot",
    niche: "ecommerce",
    categ: 13,
    price: 70,
  },
  179: {
    name: "Spin Wilds",
    niche: "ecommerce",
    categ: 14,
    price: 40,
  },
  180: {
    name: "Mega Spin World",
    niche: "ecommerce",
    categ: 13,
    price: 75,
  },
  181: {
    name: "Royal Casino Spin",
    niche: "ecommerce",
    categ: 14,
    price: 53,
  },
  182: {
    name: "Slot Paradise",
    niche: "ecommerce",
    categ: 13,
    price: 69,
  },
  183: {
    name: "Spin Palace",
    niche: "ecommerce",
    categ: 14,
    price: 65,
  },
  184: {
    name: "Jackpot Blaze",
    niche: "ecommerce",
    categ: 13,
    price: 47,
  },
  185: {
    name: "Lucky Spin Vegas",
    niche: "ecommerce",
    categ: 14,
    price: 56,
  },
  186: {
    name: "Reel Casino Stars",
    niche: "ecommerce",
    categ: 13,
    price: 71,
  },
  187: {
    name: "Spin Frenzy",
    niche: "ecommerce",
    categ: 14,
    price: 62,
  },
  188: {
    name: "Slot Championship",
    niche: "ecommerce",
    categ: 13,
    price: 78,
  },
  189: {
    name: "Vegas Paradise Slots",
    niche: "ecommerce",
    categ: 14,
    price: 55,
  },
  190: {
    name: "Golden Spin Empire",
    niche: "ecommerce",
    categ: 13,
    price: 60,
  },
  191: {
    name: "Lucky Fortune Wheel",
    niche: "ecommerce",
    categ: 14,
    price: 82,
  },
  192: {
    name: "Casino Magic",
    niche: "ecommerce",
    categ: 13,
    price: 59,
  },
};

export const NICHES_BY_ID: NichesById = {
  "all-niches": { id: "all-niches", name: "All niches", categs: [] },
  "landing-page": {
    id: "landing-page",
    name: "Landing Page",
    categs: [1, 2, 3, 4],
  },
  "sport-fantasy": {
    id: "sport-fantasy",
    name: "Sport Fantasy",
    categs: [5, 6, 7],
  },
  "social-casino": {
    id: "social-casino",
    name: "Social Casino",
    categs: [8, 9, 10, 11, 12],
  },
  ecommerce: { id: "ecommerce", name: "E-commerce", categs: [13, 14] },
};

export const CATEG_BY_ID: CategById = {
  1: { id: 1, name: "Agency", niche: "landing-page" },
  2: { id: 2, name: "Portfolio", niche: "landing-page" },
  3: { id: 3, name: "SaaS", niche: "landing-page" },
  4: { id: 4, name: "Startup", niche: "landing-page" },
  5: { id: 5, name: "Football", niche: "sport-fantasy" },
  6: { id: 6, name: "Basketball", niche: "sport-fantasy" },
  7: { id: 7, name: "Fantasy League", niche: "sport-fantasy" },
  8: { id: 8, name: "Slots", niche: "social-casino" },
  9: { id: 9, name: "Poker", niche: "social-casino" },
  10: { id: 10, name: "Bingo", niche: "social-casino" },
  11: { id: 11, name: "Roulette", niche: "social-casino" },
  12: { id: 12, name: "Blackjack", niche: "social-casino" },
  13: { id: 13, name: "Fashion", niche: "ecommerce" },
  14: { id: 14, name: "Electronics", niche: "ecommerce" },
};
